#ifndef LVGL_SIMULATOR_PROTOCOL_H
#define LVGL_SIMULATOR_PROTOCOL_H

#define LVGL_PREVIEW_PROTOCOL_NAME "lvgl-preview"
#define LVGL_PREVIEW_PROTOCOL_VERSION 1

#define LVGL_PREVIEW_COMMAND_RENDER "render"
#define LVGL_PREVIEW_COMMAND_RELOAD "reload"
#define LVGL_PREVIEW_COMMAND_SHUTDOWN "shutdown"
#define LVGL_PREVIEW_COMMAND_HIGHLIGHT "highlight"

#endif
